name: BUILD SERVICENODE

on:
  workflow_dispatch:
    inputs:
      image:
        description: Name of wallet.
        required: true
        default: servicenode
      version:
        description: Version tag to apply to image (example v4.3.3)
        required: true
      branch:
        description: Branch name (example 4.3.3)
        required: true
      repo:
        description: DockerHub repo name.
        required: true
        default: blocknetdx

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.org_blocknetdximg_password }} | docker login --username ${{ secrets.org_blocknetdximg_username }} --password-stdin

    # Build images
    - name: INFO BUILD
      run: echo ${{ github.event.inputs.image }} ${{ github.event.inputs.version }} ${{ github.event.inputs.branch }}
    - name: build an image
      run: ./ci.sh build "${{ github.event.inputs.image }}" "${{ github.event.inputs.version }}" "${{ github.event.inputs.branch }}" "${{ github.event.inputs.repo }}"
    - name: Run a container
      run: ./ci.sh run "${{ github.event.inputs.image }}" "${{ github.event.inputs.version }}" "*" "${{ github.event.inputs.repo }}"
    - name: Test build
      run: ./ci.sh test "${{ github.event.inputs.image }}" "${{ github.event.inputs.version }}"
    - name: Remove a container
      run: ./ci.sh clean "${{ github.event.inputs.image }}" "${{ github.event.inputs.version }}"
    - name: Remove dangling images
      if: ${{ always() }}
      run: yes | docker image prune
    - name: Push an image to DockerHub
      run: ./ci.sh push "${{ github.event.inputs.image }}" "${{ github.event.inputs.version }}" "*" "${{ github.event.inputs.repo }}"

#  staging:
#    if: ${{ github.event.pull_request }}
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Test new image
#      run: echo "Some test"

