name: BUILD CUSTOM IMAGE

on:
  workflow_dispatch:
    inputs:
      image:
        description: The full name of the wallet. Example - bitcoin, dash, blocknet.
        required: true
      version:
        description: Version (this will also be used in the tag of the image).
        required: true
        default: latest
      path:
        description: Full raw path of a branch where the config can be found.
        required: false
        default: https://raw.githubusercontent.com/blocknetdx/blockchain-configuration-files/master
      repo:
        description: DockerHub repo name.
        required: true
        default: blocknetdx

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.org_blocknetdximg_password }} | docker login --username ${{ secrets.org_blocknetdximg_username }} --password-stdin

    # Build images
    - name: INFO BUILD
      run: echo ${{ github.event.inputs.image }} ${{ github.event.inputs.version }}
    - name: build an image
      run: ./ci.sh build "${{ github.event.inputs.image }}" "${{ github.event.inputs.version }}" "*" "${{ github.events.inputs.repo }}"
    - name: Remove dangling images
      if: ${{ always() }}
      run: yes | docker image prune
    - name: Push an image to DockerHub
      run: ./ci.sh push "${{ github.event.inputs.image }}" "${{ github.event.inputs.version }}" "*" "${{ github.events.inputs.repo }}"

#  staging:
#    if: ${{ github.event.pull_request }}
#    needs: build
#    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Test new image
#      run: echo "Some test"

