name: RELEASE IMAGE

on:
  workflow_dispatch:
    inputs:
      name:
        description: The full name of the wallet. Example - bitcoin, dash, blocknet.
        required: true
      version:
        description: Version (this will also be used in the tag of the image).
        required: true
      repo:
        description: DockerHub repo name.
        required: true
        default: blocknetdx

jobs:

  release:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.org_blocknetdximg_password }} | docker login --username ${{ secrets.org_blocknetdximg_username }} --password-stdin
    - name: INFO RELEASE
      run: echo ${{ github.event.inputs.name }} ${{ github.event.inputs.version }}
    - name: Push an image to DockerHub
      run: ./ci.sh release "${{ github.event.inputs.name }}" "${{ github.event.inputs.version }}" "*" "${{ github.event.inputs.repo }}"
