name: RENAME IMAGE

on:
  workflow_dispatch:
    inputs:
      name:
        description: The full name of the wallet. Example - "dash" "bitcoin"
        required: true
      tag:
        description: The full tag of the existing docker image on Hub. Example - "v0.19.0.0-staging" - "v0.19-staging"
        required: true
      target_tag:
        description: Target image tag. Example - "v.19.0.0" - "v0.19"
        required: true


jobs:

  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.org_blocknetdximg_password }} | docker login --username ${{ secrets.org_blocknetdximg_username }} --password-stdin
    - name: RENAME IMAGE
      run: echo ${{ github.event.inputs.name }} ${{ github.event.inputs.target_name }}
    - name: Push an image to DockerHub
      run: ./rename.sh "${{ github.event.inputs.name }}" "${{ github.event.inputs.tag }}" "${{ github.event.inputs.target_tag }}"
